#!/usr/bin/env python3
"""Export the dogurdf policy actor weights into a C++ header.

Reads the dogurdf RL training checkpoint
``/home/sysu/Desktop/Project/Bruce/RL_Train/code/checkpoints/.../traj_v28/iteration_3000.pkl``
(flax ``ActorCriticMLP`` state dict), extracts the 4 actor layers, and writes:

  * ``include/strategy/policy_weights.h``  — const float arrays for the C++ MLP.
  * ``include/strategy/policy_test_ref.h`` — a fixed reference obs/action pair so
    the C++ forward pass can be checked numerically.

Run with the MJX conda env (needs jax/flax for the cross-check):

    /home/sysu/miniconda3/envs/MJX/bin/python tool/export_policy.py
"""

from __future__ import annotations

import os
import pickle
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.dirname(HERE)  # simplify/
# 训练框架（权威规格来源）
TRAIN = "/home/sysu/Desktop/Project/Bruce/RL_Train/code"
# 默认指向最新训练结果（v28_v3_resume，2026-09-03），可用 --ckpt 覆盖
CKPT = os.path.join(
    TRAIN,
    "checkpoints/dogurdf_velocity/checkpoints_20260903_001143_v28_v3_resume/"
    "iteration_2100.pkl",
)
# 实际编译用的权重在 include/strategy/（include/rl/ 已废弃）
OUT_WEIGHTS = os.path.join(PROJECT, "include/strategy/policy_weights.h")
OUT_REF = os.path.join(PROJECT, "include/strategy/policy_test_ref.h")

HIDDEN = (512, 256, 128)
ACTOR_DIM = 64
ACTION_DIM = 16


def elu(x: np.ndarray) -> np.ndarray:
    return np.where(x > 0, x, np.expm1(x)).astype(np.float32)


def forward(obs: np.ndarray, W, b) -> np.ndarray:
    x = elu(obs @ W[0] + b[0])
    x = elu(x @ W[1] + b[1])
    x = elu(x @ W[2] + b[2])
    return (x @ W[3] + b[3]).astype(np.float32)


def fmt_float(v: float) -> str:
    """Format a float32 as a C++ float literal (round-trip safe, no bare '0f')."""
    s = f"{float(v):.9g}"
    if "." not in s and "e" not in s and "E" not in s:
        s += ".0"
    return s + "f"


def write_float_array(f, name, arr):
    """Write one const float array as static const, row-major."""
    arr = np.ascontiguousarray(arr, dtype=np.float32).reshape(-1)
    f.write(f"static const float {name}[{arr.size}] = {{\n")
    for i in range(0, arr.size, 8):
        chunk = arr[i:i + 8]
        f.write("    " + ", ".join(fmt_float(v) for v in chunk) + ",\n")
    f.write("};\n\n")


def main() -> int:
    import argparse
    ap = argparse.ArgumentParser(description="导出 dogurdf actor 权重到 C++ header")
    ap.add_argument("--ckpt", default=CKPT, help="训练 checkpoint .pkl 路径")
    args = ap.parse_args()
    ckpt = args.ckpt
    if not os.path.exists(ckpt):
        print(f"ERROR: checkpoint not found: {ckpt}", file=sys.stderr)
        return 1

    with open(ckpt, "rb") as f:
        data = pickle.load(f)
    params = data["params"]["params"]

    W = [
        np.asarray(params["actor_mlp_0"]["kernel"], dtype=np.float32),
        np.asarray(params["actor_mlp_1"]["kernel"], dtype=np.float32),
        np.asarray(params["actor_mlp_2"]["kernel"], dtype=np.float32),
        np.asarray(params["actor_out"]["kernel"], dtype=np.float32),
    ]
    b = [
        np.asarray(params["actor_mlp_0"]["bias"], dtype=np.float32),
        np.asarray(params["actor_mlp_1"]["bias"], dtype=np.float32),
        np.asarray(params["actor_mlp_2"]["bias"], dtype=np.float32),
        np.asarray(params["actor_out"]["bias"], dtype=np.float32),
    ]
    print("kernel shapes:", [w.shape for w in W])
    print("bias   shapes:", [x.shape for x in b])

    # Reference obs/action for the C++ numeric check.
    rng = np.random.RandomState(0)
    obs_ref = (rng.rand(ACTOR_DIM).astype(np.float32) * 2.0 - 1.0)
    action_np = forward(obs_ref, W, b)

    # Cross-check against the flax network if importable (MJX env).
    flax_err = None
    try:
        sys.path.insert(0, os.path.join(TRAIN, "src"))
        import jax  # noqa: F401
        from networks import ActorCriticMLP

        net = ActorCriticMLP(
            action_size=ACTION_DIM,
            actor_hidden_dims=HIDDEN,
            critic_hidden_dims=HIDDEN,
            init_noise_std=1.0,
            activation="elu",
        )
        action_flax = np.asarray(
            net.apply(data["params"], jax.numpy.asarray(obs_ref[None]),
                      method=net.act)
        )[0]
        flax_err = float(np.max(np.abs(action_flax - action_np)))
        print(f"flax-vs-numpy max err: {flax_err:.3e}")
    except Exception as exc:  # pragma: no cover
        print(f"flax cross-check skipped ({type(exc).__name__}: {exc})")

    os.makedirs(os.path.dirname(OUT_WEIGHTS), exist_ok=True)

    with open(OUT_WEIGHTS, "w") as f:
        f.write("// Auto-generated by tool/export_policy.py — DO NOT EDIT.\n")
        f.write("#pragma once\n\n")
        write_float_array(f, "ACTOR_W0", W[0])
        write_float_array(f, "ACTOR_B0", b[0])
        write_float_array(f, "ACTOR_W1", W[1])
        write_float_array(f, "ACTOR_B1", b[1])
        write_float_array(f, "ACTOR_W2", W[2])
        write_float_array(f, "ACTOR_B2", b[2])
        write_float_array(f, "ACTOR_WO", W[3])
        write_float_array(f, "ACTOR_BO", b[3])

    with open(OUT_REF, "w") as f:
        f.write("// Auto-generated by tool/export_policy.py — DO NOT EDIT.\n")
        f.write("#pragma once\n\n")
        write_float_array(f, "REF_OBS", obs_ref)
        write_float_array(f, "REF_ACTION", action_np)

    print(f"wrote {OUT_WEIGHTS}")
    print(f"wrote {OUT_REF}")
    print("reference action[:6] =", action_np[:6])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
